version: "2"
services:

  jaeger:
    image: darkowlzz/jaeger-all-in-one:1.23
    restart: always
    ports:
      - "16686:16686"
      - "6831:6831"
      - "6832:6832"
      - "14268:14268"
      - "14250:14250"

  mosquitto:
    image: eclipse-mosquitto:1.6.15
    restart: always
    ports:
      - "1883:1883"

  wavplayeralsa:
    image: blumamir/wavplayeralsa
    restart: always
    ports:
      - "8080:80"
      - "9002:9002"
    volumes:
      - /home/pi/Music:/wav_files
    devices:
      - /dev/snd
    depends_on: 
      - "mosquitto"
                    
  timesyncserver:
    image: blumamir/time-sync-server
    restart: always
    ports:
      - "12321:12321/udp"

  ledsequenceservice:
    image: blumamir/led-sequence-service
    restart: always
    environment:
      SERVER_PORT: 80
      STORAGE_TYPE: git
      GIT_STORAGE_REPO: /led_sequence_repo
    ports:
      - "8082:80"
    volumes:
      - /home/pi/repos/led_sequence_repo:/led_sequence_repo

  ledobjectservice:
    image: blumamir/led-object-service
    restart: always
    environment:
      BROKER_URL: mqtt://mosquitto
      SERVER_PORT: 80
      STORAGE_TYPE: git
      GIT_STORAGE_REPO: /led_object_repo
      OTEL_EXPORTER_JAEGER_AGENT_HOST: jaeger
    ports:
      - "8081:80"
    volumes:
      - /home/pi/repos/led_object_repo:/led_object_repo
    depends_on: 
      - "mosquitto"
          
  ledtriggerservice:
    image: blumamir/led-trigger-service
    restart: always
    environment:
      APP_ENV: production
      PORT: 80
      BROKER_URL: mqtt://mosquitto
      LED_SEQ_SERVICE_IP: ledsequenceservice
      LED_SEQ_SERVICE_PORT: 80
      PLAYER_IP: wavplayeralsa
      PLAYER_PORT: 80
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      OTEL_RUBY_EXPORTER_JAEGER_SSL_VERIFY_NONE: 1
    ports:
      - "8083:80"
    depends_on: 
      - "ledsequenceservice"
      - "wavplayeralsa"
      - "mosquitto"

  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro

  grafana:
    image: grafana/grafana
    user: "$UID:$GID"
    restart: unless-stopped
    links:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources/
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=kivsee12

#volumes:
#  influxdb: 
#  grafana: 