version: "2"
services:
    mosquitto:
        image: eclipse-mosquitto
        restart: always
        ports:
            - "1883:1883"
    timesyncserver:
        image: blumamir/time-sync-server
        restart: always
        ports:
            - "12321:12321/udp"
    influxdb:
        image: influxdb
        restart: unless-stopped
        ports:
          - "8086:8086"
        volumes:
          - /home/pi/influxdb:/var/lib/influxdb
          - /home/pi/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    grafana:
        image: grafana/grafana
        restart: unless-stopped
        links:
          - influxdb
        ports:
          - "3000:3000"
        volumes:
          - /home/pi/grafana:/var/lib/grafana

#volumes:
#  influxdb: 
#  grafana: 