version: "2"
services:

    mosquitto:
        image: eclipse-mosquitto
        restart: always
        ports:
            - "1883:1883"
            
    timesyncserver:
        image: blumamir/time-sync-server
        restart: always
        ports:
            - "12321:12321/udp"
